--- 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: phm-tomcat
  namespace: pmewada
  labels:
    app: phm-tomcat
annotations:
    kubernetes.io/minikube-addons-endpoint:logviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phm-tomcat
  template:
    metadata:
      name: phm-tomcat
      creationTimestamp: null
      labels:
        app: phm-tomcat
    spec:
      containers:
        - name: phm-tomcat
          image: 'tomcat:1'
          ports: 
            - 
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
